# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_auto_20160410_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_posts',
            name='count',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_posts',
            name='image',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
